### PR TITLE
fix(patients): current patient can no longer be related person

### LINKED ISSUE #1946: Patient can also be related person
## 🐛 Bug Report

Current, when adding a related person, the current patient can be added as the related person. 

## To Reproduce

1. View patient
2. Navigate to Related Persons tab
3. Add Related Persons
4. Search for current patient in related person
5. See that current patient appears in related person

## Expected behavior
The current patient should not be returned in the results of the search if the current patient matches the search results.

### PR DESCRIPTION
**Pull request by alti21**
Fixes #1946.

**Changes proposed in this pull request:**

- Current patient cannot show up in related person search

### CODE REVIEW

File: src/patients/related-persons/AddRelatedPersonModal.tsx [hunk 1]
```diff
@@ -50,9 +55,13 @@ const AddRelatedPersonModal = (props: Props) => {
               placeholder={t('patient.relatedPerson')}
               onChange={onPatientSelect}
               onSearch={async (query: string) => PatientRepository.search(query)}
-              renderMenuItemChildren={(patient: Patient) => (
-                <div>{`${patient.fullName} (${patient.code})`}</div>
-              )}
+              renderMenuItemChildren={(patients: Patient) => {
+                if (patientCode() === patients.code) {
```
Comment (jackcmeyer) [inline src/patients/related-persons/AddRelatedPersonModal.tsx:59]: Although `code` is a unique identifier, I think it would be better to compare patient ids.

File: src/patients/related-persons/AddRelatedPersonModal.tsx [hunk 2]
```diff
@@ -50,9 +55,13 @@ const AddRelatedPersonModal = (props: Props) => {
               placeholder={t('patient.relatedPerson')}
               onChange={onPatientSelect}
               onSearch={async (query: string) => PatientRepository.search(query)}
-              renderMenuItemChildren={(patient: Patient) => (
-                <div>{`${patient.fullName} (${patient.code})`}</div>
-              )}
+              renderMenuItemChildren={(patients: Patient) => {
```
Comment (jackcmeyer) [inline src/patients/related-persons/AddRelatedPersonModal.tsx:58]: rename `patients` to `patient` to better reflect that value of the variable

File: src/patients/related-persons/AddRelatedPersonModal.tsx [hunk 3]
```diff
@@ -50,9 +55,13 @@ const AddRelatedPersonModal = (props: Props) => {
...
+                if (patientCode() === patients.code) {
+                  return <div />
+                }
+
+                return <div>{`${patients.fullName} (${patients.code})`}</div>
```
Comment (jackcmeyer) [inline src/patients/related-persons/AddRelatedPersonModal.tsx:63]: Can we add a test proving that the current patient does not come in this list?

**Comment by jackcmeyer** [comment]
@alti21 I was able to fix the lint errors from master, so no need to worry about those.

File: src/patients/related-persons/AddRelatedPersonModal.tsx (hunk 2 above)
Comment (jackcmeyer) [reply src/patients/related-persons/AddRelatedPersonModal.tsx:58]: Ohhh, good point. Maybe we just go with `p`

File: src/patients/related-persons/AddRelatedPersonModal.tsx (hunk 3 above)
Comment (alti21) [reply src/patients/related-persons/AddRelatedPersonModal.tsx]: Hi @jackcmeyer I'm not too familiar with Jest testing, I can try to figure it out, but i'm having some trouble doing so

Comment (jackcmeyer) [reply src/patients/related-persons/AddRelatedPersonModal.tsx]: No worries! Feel free to reach out on slack if you need any help

**Comment by jackcmeyer** [comment]
Thanks for the contribution @alti21!
