### PR TITLE
ember-intl implementation fixes

### LINKED ISSUE #1561: ember-intl upgrade side effects
**Expected behavior:**
Warning message should have no HTML in it.
**Actual behavior:**
Warning message has HTML in it.

**Steps to reproduce:**
_New Inventory Item Add_
1. Login
2. Click on Inventory Received 
3. Click on add button
4. View the message with HTML in it

OR 
_New Patient Quick Add_
1. Login
2. Click on Medication -> New Request
3. Enter patient name that doesn't exist
4. Fill in other information
5. View error message

**Screenshots (if applicable):**
_New Inventory Item Add_
image

_New Patient Quick Add_
image

**OS and Browser:**
MacOS, Chrome 70, Firefox, Safari

- [x] warning messages which use HTML to render are showing the raw html in the message
- [x] unable to select first lanaguage
- [x] navigation bar items not being translated
- [ ] warnings with Hebrew in the console and some Hebrew messages not rendering
- [x] default to English for missing translations
- [x] different results between missing translations and empty translations
- [x] loss of support of right-to-left languages

### PR DESCRIPTION
**Pull request by chadian**
Partially fixes #1561.

* remove empty string translations
* setting a missing translation message to an empty string
* Adding the fallback locale

cc @HospitalRun/core-maintainers

### CODE REVIEW

File: app/services/language-preference.js [hunk 1]
```diff
@@ -1,10 +1,8 @@
 import { run } from '@ember/runloop';
-import { getOwner } from '@ember/application';
 import { hash } from 'rsvp';
 import Service, { inject as service } from '@ember/service';
 import Ember from 'ember';
 import config from '../config/environment';
-import { walkConfigs, setRTL } from '../utils/locale-utils';
```
Comment (chadian) [inline app/services/language-preference.js]: These were removed along with the corresponding files since they don't relate to `ember-intl` anymore and were caught in my find/replace for `ember-i18n` to `ember-intl`. Is there a way I can verify that RTL is working properly with `ember-intl` in the same way it was before with `ember-i18n`?

Comment (MatthewDorner) [reply app/services/language-preference.js]: I think there was one included locale that used that, Urdu. I remember it caused the entire nav bar to move to the right side of the screen instead of left. There's this https://github.com/HospitalRun/hospitalrun-frontend/issues/1247.

**Comment by MatthewDorner** [comment]
Took a look at the RTL with Urdu language, looks good except I noticed something else: the font changes. It even sometimes changes in the middle of a translation item, and there's no HTML or anything in the translation string, I wonder what it is. And I don't see this in any other locale even other RTL ones.

rtl urdu

Also noticed some additional issues that were also present before the switch to intl so I can make a new issue for those later.

**Comment by chadian** [comment]
That's really interesting actually. I can't explain the font change for urdu. The characters look like they could be the same, I'm not sure if the change is acceptable or not either. I agree, let's do this as a separate issue and I'm happy to also investigate. Nothing else for this PR from my end, thanks! 👍

**Comment by MatthewDorner** [comment]
The characters look to be identical, just different font so I doubt it's a big deal. Thanks for the quick fixes.

**Comment by MatthewDorner** [comment]
Actually one more thing occurs to me, in https://github.com/HospitalRun/hospitalrun-frontend/pull/1458 we set all those translation keys to undefined instead of removing them so people could more easily see in the file what keys need to be translated.

Would it be better to comment them out instead of removing them entirely?

**Comment by MatthewDorner** [comment]
Maybe that's not a good idea either since if people add keys, they'll just forget to add commented out keys in the other languages so they still won't stay synced up.
