### PR TITLE
Enhancement/move modal to inline

### LINKED ISSUE #377: Show patient update confirmation as inline alert rather than modal
**Current experience:** When you update a patient record, you are shown a confirmation dialog as a modal that lets you go back, or simply close the dialog. It is superfluous and requires an extra click to keep working if you don't want to return to the patient record screen.

image

**Better experience:** Instead, we should render the alert inline just above the button so that you don't have the extra step of dismissing the modal if you want to do anything other than returning to the patient index. We can still include the patient index link in the confirmation alert for convenience if that is your next destination.

**Steps to reproduce:** Go to a patient record and update any piece of information.

### PR DESCRIPTION
**Pull request by dasManaswini**
Fixes #377 
Progress in work of #958 and #973 

**Changes proposed in this pull request:**
- Inline alert for edit button added
- Fixed Travis error of #958 (double quotes changed to single quote)

one

cc @jkleinsc @jglovier

### CODE REVIEW

**Comment by jkleinsc** [comment]
@dasManaswini - I took a look at the failing tests and I realized the tests are failing because of the change you made.  The reason is that the tests are expecting the modal to appear when the patient is saved.
The following tests are expecting the modal to appear:
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/tests/acceptance/patient-notes-test.js#L24-L27
and
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/tests/acceptance/patients-test.js#L90-L94

Those lines need to be changed to instead detect the inline message and then the tests should pass.  Let me know if you need any help or further instruction on this.

**Comment by dasManaswini** [comment]
@jkleinsc I have changed those test cases that you had mentioned, still I am getting some errors. Can you please help me debug those errors?

**Comment by jkleinsc** [comment]
@dasManaswini I'll take a look today and see what the problem is.

File: tests/acceptance/patients-test.js [hunk 1]
```diff
@@ -87,9 +87,9 @@ test('Adding a new patient record', function(assert) {
     fillIn('.test-first-name input', 'John');
     fillIn('.test-last-name input', 'Doe');
     click('.panel-footer button:contains(Add)');
-    waitToAppear('.modal-dialog');
+    waitToAppear('.message');
     andThen(function() {
-      assert.equal(find('.modal-title').text(), 'Patient Saved', 'Patient record has been saved');
+      assert.equal(find('.message').text(), 'Patient Saved', 'Patient record has been saved');
       assert.equal(find('.modal-body').text().trim(), 'The patient record for John Doe has been saved.', 'Record has been saved');
```
Comment (jkleinsc) [inline tests/acceptance/patients-test.js]: This test is failing because .modal-body isn't displayed, .message is

File: tests/acceptance/patients-test.js [hunk 2]
```diff
@@ -87,9 +87,9 @@ test('Adding a new patient record', function(assert) {
     fillIn('.test-first-name input', 'John');
     fillIn('.test-last-name input', 'Doe');
     click('.panel-footer button:contains(Add)');
-    waitToAppear('.modal-dialog');
+    waitToAppear('.message');
     andThen(function() {
-      assert.equal(find('.modal-title').text(), 'Patient Saved', 'Patient record has been saved');
+      assert.equal(find('.message').text(), 'Patient Saved', 'Patient record has been saved');
```
Comment (jkleinsc) [inline tests/acceptance/patients-test.js]: the text you are looking to find should be 'The patient record for John Doe has been saved.', not 'Patient Saved'

File: tests/acceptance/patient-notes-test.js [hunk 3]
```diff
@@ -21,10 +21,10 @@ test('patient notes crud testing', function(assert) {
       fillIn('.test-first-name input', 'John');
       fillIn('.test-last-name input', 'Doe');
       click('.panel-footer button:contains(Add)');
-      waitToAppear('.modal-dialog');
+      waitToAppear('.message');
     });
     andThen(function() {
-      assert.equal(find('.modal-title').text(), 'Patient Saved', 'Patient record has been saved');
+      assert.equal(find('.message').text(), 'Patient Saved', 'Patient record has been saved');
```
Comment (jkleinsc) [inline tests/acceptance/patient-notes-test.js]: the text you are looking to find should be 'The patient record for John Doe has been saved.', not 'Patient Saved'

File: tests/acceptance/patients-test.js (hunk 2 above)
Comment (jkleinsc) [inline tests/acceptance/patients-test.js]: the modal close shouldn't be here

**Comment by jkleinsc** [comment]
@dasManaswini one more thing in looking at the tests.  The following code in the tests:
```js
waitToAppear('.message');
```
should be changed to:
```js
waitToAppear('.message:contains(The patient record for John Doe has been saved)');
```

**Comment by dasManaswini** [comment]
Thanks a lot for your guidance @jkleinsc I have made necessary changes as you had mentioned.

File: tests/acceptance/patients-test.js [hunk 4]
```diff
@@ -1,179 +1,150 @@
...
-      waitToAppear('.panel-title');
-
-      andThen(() => {
-        let exportReportButton = findWithAssert('a:contains(Export Report)');
-        assert.equal($(exportReportButton).attr('download'), `${reportName} Report 12/11/2016 - 12/31/2016.csv`);
-      });
-    });
-  });
-}
+ import Ember from 'ember';
```
Comment (jkleinsc) [inline tests/acceptance/patients-test.js]: Did you reformat this file?  It appears as though the whole file has been changed.

Comment (dasManaswini) [inline tests/acceptance/patients-test.js]: @jkleinsc I had used eslint to fix the errors of the particular file.May be because of that the whole file appears to be reformatted.I am going to replace the existing file with the previous one so that you can easily merge it.

**Comment by dasManaswini** [comment]
@jkleinsc I have updated the branch with the necessary modifications. Please let me know if any further changes are to be made.

**Comment by jkleinsc** [comment]
Thanks for sticking with this PR @dasManaswini!  I think its ready to go, so I am going to merge it in.
