### PR TITLE
Fix 1014

### LINKED ISSUE #1014: Discharge report - use the examiner field from the visit.
**Expected behavior:**

The discharge report should pull the "examiner" field off the associated admission visit.   So, on the report, it is a read only field. 

**Actual behavior:**

The report is presenting a drop-down to the user labeled "surgeon"

**Steps to reproduce:**

1. create a visit of type admission for a patient
2.  create a new discharge report, view the surgeon field

**Screenshots (if applicable):**

**OS and Browser:**

@jkleinsc

### PR DESCRIPTION
**Pull request by adeolabadmus**
Fixes #1014

cc @HospitalRun/core-maintainers

### CODE REVIEW

File: app/locales/en/translations.js [hunk 1]
```diff
@@ -1241,7 +1241,8 @@ export default {
         author: 'Author'
       },
       visitType: 'Visit Type',
-      examiner: 'Visit Examiner',
+      visitExaminer: 'Visit Examiner',
```
Comment (jkleinsc) [inline app/locales/en/translations.js]: We don't need two different labels here.  Just use Examiner.

File: app/visits/reports/edit/template.hbs [hunk 2]
```diff
@@ -55,7 +55,7 @@
 
           {{#if visit.examiner }}
             <div class="ps-info-group test-examiner">
-              <p><b class="test-examiner-label">{{t 'reports.labels.examiner' }}:</b>
+              <p><b class="test-examiner-label">{{t 'reports.labels.visitExaminer' }}:</b>
```
Comment (jkleinsc) [inline app/visits/reports/edit/template.hbs]: use reports.labels.examiner instead of reports.labels.visitExaminer.

File: app/visits/reports/edit/template.hbs [hunk 3]
```diff
@@ -181,13 +181,12 @@
             <span class="test-visit-discharge-date-data">{{date-format model.reportDate format="DD/MM/YYYY"}}</span>
```
Comment (jkleinsc) [inline app/visits/reports/edit/template.hbs]: I didn't notice this before -- this shouldn't be specifying a date format, it should use the default for the data-helper, which is the locale specific date.  Please take off the ```format="DD/MM/YYYY"```

**Comment by adeolabadmus** [comment]
@jkleinsc Changes have been effected.

**Comment by jkleinsc** [comment]
Looks good to me @adeolabadmus. Thanks for updating!  I'll merge it in.
